org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=/root/.local/share/mise/installs/java/17.0.2
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
org.gradle.daemon=false
org.gradle.parallel=false
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.http.keepAlive=true
systemProp.https.keepAlive=true
